# Camera, sensor, and motor constants:

# CAMERA PARAMETERS
# Resolution (in pixels) for SONY IMX571 APS-C sensor
HORIZONTAL_RESOLUTION = 6224           # pixels (int)
VERTICAL_RESOLUTION   = 4168           # pixels (int)
PIXEL_SIZE            = 0.00376        # mm (float)
HORIZONTAL_SENSOR_DIMENSION = 23.40224 # mm (float)
VERTICAL_SENSOR_DIMENSION   = 15.67168 # mm (float)
FOCAL_LENGTH          = 100            # mm (float)

# MOTOR PARAMETERS
# Horizontal motor
ENCODER_HORIZONTAL_MOTOR      = 262144  # steps per revolution (int)
HORIZONTAL_ENCODER_MULTIPLIER = 4       # multiplier (int)
HORIZONTAL_MOTOR_GEARBOX_RATIO= 80      # ratio (int)
HORIZONTAL_MOTOR_NAME         = axis_1002 # motor for horizontal movement

# Vertical motor
ENCODER_VERTICAL_MOTOR        = 262144  # steps per revolution (int)
VERTICAL_ENCODER_MULTIPLIER   = 4       # multiplier (int)
VERTICAL_MOTOR_GEARBOX_RATIO  = 80      # ratio (int)
VERTICAL_MOTOR_NAME           = axis_1001 # motor for vertical movement


# STARTING COMMANDS

# Run:
# python3 Examples/EcMasterDemoMotion/menu_base.py


# Cd /home/agx/ethercat/EC-Master/Bin/Linux/aarch64/Release
# Sudo ./EcMasterDemoMotion DemoConfig.xml
# Nohup ./motor_controller > motor_controller.log 2>&1 &
# python3 Examples/EcMasterDemoMotion/menu_base.py 


# One-command start (supervised):
# bash /home/agx/ethercat/EC-Master/Examples/EcMasterDemoMotion/start_follow_supervised.sh
# This starts generator, controller, and the demo (with sudo) in the correct order.

# One-command stop:
# bash /home/agx/ethercat/EC-Master/Examples/EcMasterDemoMotion/stop_follow_supervised.sh
# This stops the generator, controller, and the demo (with sudo) in the correct order.